---

# @see https://github.com/EticaAI/aguia-pescadora/issues/5
# @see https://github.com/EticaAI/aguia-pescadora/tree/master/diario-de-bordo/tsuru-inicializacao++
# @see https://github.com/fititnt/cplp-aiops/blob/master/logbook/aguia-pescadora-charlie.sh

# ansible-playbook 1-node-tsuru-autossl.yml -e paas_host=example.com
# ansible-playbook 1-node-tsuru-autossl.yml -e paas_host=aguia-pescadora-foxtrot.etica.ai

- name: tldr tsuru client? docker? docker-machine?
  hosts: localhost
  tasks:
    - name: tsuru client? https://tsuru-client.readthedocs.io/en/latest/installing.html
      shell: tsuru --version
      register: result
      changed_when: false
      ignore_errors: false

    - name: docker? https://docs.docker.com/install/
      shell: docker --version
      register: result2
      changed_when: false
      ignore_errors: false

    - name: docker-machine? https://docs.docker.com/machine/install-machine/
      shell: docker-machine version
      register: result3
      changed_when: false
      ignore_errors: false

- name: "Águia Pescadora PaaS Tudo-Em-Um-Nó (Tsuru PaaS, Minio, AutoSSL via OpenResty)"
  hosts: all
  remote_user: root
  vars:
    paas_host: "{{ inventory_hostname }}"
    # tsuru_target: "tsuru.{{paas_host}}
    # apps_domain: "app.{{paas_host}}"

  roles:
    - common
    - minio
    - 1-node-tsuru-autossl
