---

# @see https://github.com/EticaAI/aguia-pescadora/issues/5
# @see https://github.com/EticaAI/aguia-pescadora/tree/master/diario-de-bordo/tsuru-inicializacao++
# @see https://github.com/fititnt/cplp-aiops/blob/master/logbook/aguia-pescadora-charlie.sh

# ansible-playbook 1-node-tsuru-autossl.yml -e paas_host=example.com
# ansible-playbook 1-node-tsuru-autossl.yml -e paas_host=aguia-pescadora-foxtrot.etica.ai

#- name: 'debug'
#  hosts: all
#  tasks:
#  - name: debug tsuru_init_configs
#    debug:
#      msg: Debug ansible_host {{ ansible_facts['default_ipv4']['address'] }}

- name: "localhost: tsuru client? docker? docker-machine?"
  hosts: localhost
  roles:
    - tsuru-installer
    # - { role: 1-node-tsuru-autossl, tsuru_initialization_only: yes }

- name: "Águia Pescadora PaaS Tudo-Em-Um-Nó (Tsuru PaaS, Minio, AutoSSL via OpenResty)"
  hosts: all
  remote_user: root
  vars:
    paas_host: "{{ inventory_hostname }}"
    # tsuru_target: "tsuru.{{paas_host}}
    # apps_domain: "app.{{paas_host}}"

  roles:
    - common
    - minio
    # - { role: 1-node-tsuru-autossl, tsuru_initialization_only: no }
