---

# @see https://github.com/EticaAI/aguia-pescadora/issues/5
# @see https://github.com/EticaAI/aguia-pescadora/tree/master/diario-de-bordo/tsuru-inicializacao++
# @see https://github.com/fititnt/cplp-aiops/blob/master/logbook/aguia-pescadora-charlie.sh

# ansible-playbook 1-node-tsuru-autossl.yml -e paas_host=example.com
# ansible-playbook 1-node-tsuru-autossl.yml -e paas_host=aguia-pescadora-foxtrot.etica.ai

#- name: 'debug'
#  hosts: all
#  tasks:
#  - name: debug tsuru_init_configs
#    debug:
#      msg: Debug {{ hostvars[groups['all'][0]]['ansible_facts']['default_ipv4']['address'] }} // ansible_host {{ ansible_facts['all_ipv4_addresses'][0] }} paas_cluster_name {{ paas_cluster_name }}
#      #msg: Debug {{ hostvars[groups['all'][0]]['default_ipv4']['address'] }} // ansible_host {{ ansible_facts['all_ipv4_addresses'][0] }} paas_cluster_name {{ paas_cluster_name }}

# TODO: mover o role de tsuru-install para o final deste arquivo (fititnt, 2019-07-03 22:21 BRT)

- name: "localhost: tsuru client? docker? docker-machine?"
  hosts: localhost
  vars:
    paas_master_ip: "{{ hostvars[groups['all'][0]]['ansible_facts']['default_ipv4']['address'] }}"
    paas_node1_ip: "{{ hostvars[groups['all'][0]]['ansible_facts']['default_ipv4']['address'] }}"
#  tasks:
#  - name: 'debug'
#    debug:
#      msg: debug {{ hostvars[groups['all'][0]] }}
  roles:
    - tsuru-installer
    # - { role: 1-node-tsuru-autossl, tsuru_initialization_only: yes }

- name: "Águia Pescadora PaaS Tudo-Em-Um-Nó (Tsuru PaaS, Minio, AutoSSL via OpenResty)"
  hosts: all
  remote_user: root
  vars:
    paas_host: "{{ inventory_hostname }}"
    # tsuru_target: "tsuru.{{paas_host}}
    # apps_domain: "app.{{paas_host}}"

  roles:
    - common
    - minio
    # - { role: 1-node-tsuru-autossl, tsuru_initialization_only: no }
