---
# https://www.wikiaves.com.br/wiki/macarico-solitario
#   "Habita locais à beira d'água doce, margens lamacentas de rios e lagos,
#    poças de chuva maiores, especialmente quando localizadas em campos com
#    árvores. Normalmente encontrado solitário, às vezes em 2 ou 3 indivíduos
#    espalhados, mas nunca em grupos."

# @TODO: iniciar modo de 1 nó, com Kubernetes

- name: "macarico-solitario"
  hosts: all
  remote_user: root
  vars:
    paas_host: "{{ inventory_hostname }}"
    # tsuru_target: "tsuru.{{paas_host}}
    # apps_domain: "app.{{paas_host}}"

  roles:
    - common
    - ap-kubernetes
    # - minio
    # - paas-host
