---
- name: Cluster Águia Pescadora da Etica.AI
  hosts: all
  remote_user: root

  roles:
    - common
#    - mysql
#    - nginx
#    - php-fpm
#    - wordpress

# https://docs.ansible.com/ansible/latest/modules/hostname_module.html