---
# openresty-luarocks-lua-resty-auto-ssl-install.yml

# openresty errors:
# tail -f /usr/local/openresty/nginx/logs/error.log


## openresty? luarocks? lua-resty-auto-ssl? ____________________________________
- name: "openresty?"
  shell: openresty -v
  register: is_openresty
  changed_when: false
  ignore_errors: true

- name: "luarocks?"
  shell: luarocks --version
  register: is_luarocks
  changed_when: false
  ignore_errors: true

- name: "lua-resty-auto-ssl?"
  stat:
    path: /etc/resty-auto-ssl
  register: is_restyautossl
  #register: restyautossl_folder

## apt install -y openresty ____________________________________________________

- name: "software-properties-common: apt install -y software-properties-common"
  apt:
    name: software-properties-common
  when: is_openresty is failed

- name: "openresty: apt-key add"
  apt_key:
    url: https://openresty.org/package/pubkey.gpg 
    state: present
  when: is_openresty is failed

- name: "openresty: add-apt-repository (...)"
  apt_repository:
    repo: 'deb http://openresty.org/package/ubuntu bionic main' 
    state: present
    filename: openresty
    update_cache: yes
  when: is_openresty is failed

- name: "openresty: apt install -y openresty"
  apt:
    name: openresty
    state: present
    update_cache: yes
  when: is_openresty is failed

## apt install -y luarocks _____________________________________________________
- name: "luarocks: apt install -y luarocks"
  apt:
    name: luarocks
    state: present
    update_cache: yes
  when: is_luarocks is failed

## luarocks install lua-resty-auto-ssl _________________________________________
# @see https://github.com/GUI/lua-resty-auto-ssl#installation

- name: 'sudo mkdir /etc/resty-auto-ssl ; sudo chown www-data /etc/resty-auto-ssl'
  file:
    state: directory
    path: /etc/resty-auto-ssl
    owner: www-data
    group: www-data
  when: is_luarocks is failed

- name: "resty-auto-ssl: sudo luarocks install lua-resty-auto-ssl"
  shell: luarocks install lua-resty-auto-ssl
  register: is_restyautossl2
  # when: restyautossl_folder.stat.isdir is defined and restyautossl_folder.stat.isdir
  when: is_luarocks is failed

# TODO: trocar comando seguinte de 'shell' para 'lineinfile' ou 'template' fititnt, 2019-07-01 06:33 BRT)
# @see https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
- name: "hotfix 'err: Can't load ./.rnd into RNG', https://github.com/openssl/openssl/issues/7754#issuecomment-444063355"
  shell: sed -i '/RANDFILE/s/^/#/g' /etc/ssl/openssl.cnf
  register: is_restyautossl_hotfix_openssl
  # when: restyautossl_folder.stat.isdir is defined and restyautossl_folder.stat.isdir
  when: is_luarocks is failed

- name: "sudo openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj '/CN=sni-support-required-for-valid-ssl' -keyout /etc/ssl/resty-auto-ssl-fallback.key -out /etc/ssl/resty-auto-ssl-fallback.crt"
  shell: openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj '/CN=sni-support-required-for-valid-ssl' -keyout /etc/ssl/resty-auto-ssl-fallback.key -out /etc/ssl/resty-auto-ssl-fallback.crt
  become: yes
  register: is_restyautossl_fallbackkey
  #when: restyautossl_folder.stat.isdir is defined and restyautossl_folder.stat.isdir

# TODO: resolver problema de fallbackkey não estar sendo criada automaticamente (fititnt, 2019-07-03 23:34 BRT)
