---

- name: /usr/local/openresty/nginx/html/index.html
  template:
    src: roles/paas-host/templates/openresty/nginx/html/index.html.j2
    dest: /usr/local/openresty/nginx/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/html/favicon.ico
  template:
    src: roles/paas-host/templates/openresty/nginx/html/favicon.ico
    dest: /usr/local/openresty/nginx/html/favicon.ico
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/html/robots.txt
  template:
    src: roles/paas-host/templates/openresty/nginx/html/robots.txt
    dest: /usr/local/openresty/nginx/html/robots.txt
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/html/404.html
  template:
    src: roles/paas-host/templates/openresty/nginx/html/404.html.j2
    dest: /usr/local/openresty/nginx/html/404.html
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/html/50x.html
  template:
    src: roles/paas-host/templates/openresty/nginx/html/50x.html.j2
    dest: /usr/local/openresty/nginx/html/50x.html
    owner: root
    group: root
    mode: '0644'

- name: /usr/local/openresty/nginx/conf/nginx.conf
  template:
    src: roles/paas-host/templates/openresty/nginx/conf/nginx.conf.j2
    dest: /usr/local/openresty/nginx/conf/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - reload openresty
