---
# tasks file for common

- name: Set Hostname
  hostname:
    name: "{{ inventory_hostname }}"

# sudo timedatectl set-timezone UTC

#- name: Prepara todos os hosts
#  tasks:
#  - name: Teste teste net-tools
#    apt:
#      name: '{{ item }}'
#      state: installed
#    with_items:
#    - net-tools