---
# tasks file for common

#- name: debug ansible_hostname
#  debug:
#    msg: debug {{ ansible_facts['date_time']['tz'] }}

## Por segurança talvez a pessoa pode não ter lido manual e não saber que não 
## testamos nos demais sistemas operacionais.
- name: Ubuntu? Debian?
  fail:
    msg: fail
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

- name: sudo apt-get install aptitude
  apt:
   name: aptitude
   state: present

- name: sudo hostnamectl set-hostname {{ inventory_hostname }}
  hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname_short != ansible_hostname

- name: sudo timedatectl set-timezone UTC
  timezone:
    name: UTC
  when: ansible_facts['date_time']['tz'] != 'UTC'

# sudo timedatectl set-timezone UTC

#- name: Prepara todos os hosts
#  tasks:
#  - name: Teste teste net-tools
#    apt:
#      name: '{{ item }}'
#      state: installed
#    with_items:
#    - net-tools
