---
# tasks file for common

- fail:
    msg: Ubuntu? Debian? Fail. Not fully tested on other OSs.
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: sudo apt-get install aptitude
  apt:
   name: aptitude
   state: present
  # when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: sudo hostnamectl set-hostname {{ inventory_hostname }}
  hostname:
    name: "{{ inventory_hostname }}"

- name: sudo timedatectl set-timezone UTC
  timezone:
    name: UTC

# sudo timedatectl set-timezone UTC

#- name: Prepara todos os hosts
#  tasks:
#  - name: Teste teste net-tools
#    apt:
#      name: '{{ item }}'
#      state: installed
#    with_items:
#    - net-tools
